### ISSUE TITLE
The code for our vehicle ReID and parsing paper has just released.

### ISSUE THREAD

**Issue by lxc86739795** [layumi/Vehicle_reID-Collection#3]
Hi Zhedong,
The code for our parsing-guided vehicle ReID paper in ACM MM 2020 has just released.
The paper is here: https://lxc86739795.github.io/papers/2020_ACMMM_PCRNet.pdf.
The code is here: https://github.com/lxc86739795/vehicle_reid_by_parsing.
A codebase for human and vehicle parsing can be found here: https://github.com/lxc86739795/parsing_platform.

Best,
Xinchen

**Comment by layumi** [comment]
Thanks a lot. I have updated the README.
